---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rokhir/public_html/casting-portal/
    - export MUPATH=/home/rokhir/public_html/wp-content/mu-plugins/
    - /bin/rm -f $MUPATH/casting-wp-admin-guard-loader.php
    - /bin/cp -R * $DEPLOYPATH
    - /bin/mkdir -p $MUPATH
    - /bin/cp $DEPLOYPATH/mu-plugin/casting-wp-admin-guard.php $MUPATH/casting-wp-admin-guard.php
